// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfo.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.AdvInfo}
 */
public final class AdvInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.AdvInfo)
    AdvInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdvInfo.newBuilder() to construct.
  private AdvInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdvInfo() {
    caption_ = "";
    fields_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdvInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdvInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            caption_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fields_ = new java.util.ArrayList<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef>();
              mutable_bitField0_ |= 0x00000001;
            }
            fields_.add(
                input.readMessage(com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.racerssquad.besthack2023.DTO.proto.AdvInfoData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fields_ = java.util.Collections.unmodifiableList(fields_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.AdvInfoProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.AdvInfoProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.AdvInfo.class, com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder.class);
  }

  private int bitField0_;
  public static final int CAPTION_FIELD_NUMBER = 1;
  private volatile Object caption_;
  /**
   * <pre>
   * Заголовок
   * </pre>
   *
   * <code>string caption = 1;</code>
   * @return The caption.
   */
  @Override
  public String getCaption() {
    Object ref = caption_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      caption_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Заголовок
   * </pre>
   *
   * <code>string caption = 1;</code>
   * @return The bytes for caption.
   */
  @Override
  public com.google.protobuf.ByteString
      getCaptionBytes() {
    Object ref = caption_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      caption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDS_FIELD_NUMBER = 2;
  private java.util.List<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef> fields_;
  /**
   * <pre>
   * Список описания полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
   */
  @Override
  public java.util.List<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef> getFieldsList() {
    return fields_;
  }
  /**
   * <pre>
   * Список описания полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
   */
  @Override
  public java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder> 
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <pre>
   * Список описания полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
   */
  @Override
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <pre>
   * Список описания полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <pre>
   * Список описания полей
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.racerssquad.besthack2023.DTO.proto.AdvInfoData data_;
  /**
   * <pre>
   * Данные
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
   * @return Whether the data field is set.
   */
  @Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Данные
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
   * @return The data.
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoData getData() {
    return data_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfoData.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * Данные
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoDataOrBuilder getDataOrBuilder() {
    return data_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfoData.getDefaultInstance() : data_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCaptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, caption_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(2, fields_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getData());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCaptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, caption_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, fields_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.AdvInfo)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.AdvInfo other = (com.racerssquad.besthack2023.DTO.proto.AdvInfo) obj;

    if (!getCaption()
        .equals(other.getCaption())) return false;
    if (!getFieldsList()
        .equals(other.getFieldsList())) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCaption().hashCode();
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.AdvInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.AdvInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.AdvInfo)
      com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.AdvInfo.class, com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.AdvInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldsFieldBuilder();
        getDataFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      caption_ = "";

      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fieldsBuilder_.clear();
      }
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfo_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfo getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfo build() {
      com.racerssquad.besthack2023.DTO.proto.AdvInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfo buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.AdvInfo result = new com.racerssquad.besthack2023.DTO.proto.AdvInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.caption_ = caption_;
      if (fieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
      } else {
        result.fields_ = fieldsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.AdvInfo) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.AdvInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.AdvInfo other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getCaption().isEmpty()) {
        caption_ = other.caption_;
        onChanged();
      }
      if (fieldsBuilder_ == null) {
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
      } else {
        if (!other.fields_.isEmpty()) {
          if (fieldsBuilder_.isEmpty()) {
            fieldsBuilder_.dispose();
            fieldsBuilder_ = null;
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldsFieldBuilder() : null;
          } else {
            fieldsBuilder_.addAllMessages(other.fields_);
          }
        }
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.AdvInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.AdvInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object caption_ = "";
    /**
     * <pre>
     * Заголовок
     * </pre>
     *
     * <code>string caption = 1;</code>
     * @return The caption.
     */
    public String getCaption() {
      Object ref = caption_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        caption_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Заголовок
     * </pre>
     *
     * <code>string caption = 1;</code>
     * @return The bytes for caption.
     */
    public com.google.protobuf.ByteString
        getCaptionBytes() {
      Object ref = caption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        caption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Заголовок
     * </pre>
     *
     * <code>string caption = 1;</code>
     * @param value The caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaption(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      caption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок
     * </pre>
     *
     * <code>string caption = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCaption() {
      
      caption_ = getDefaultInstance().getCaption();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок
     * </pre>
     *
     * <code>string caption = 1;</code>
     * @param value The bytes for caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      caption_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef> fields_ =
      java.util.Collections.emptyList();
    private void ensureFieldsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fields_ = new java.util.ArrayList<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef>(fields_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder> fieldsBuilder_;

    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public java.util.List<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef> getFieldsList() {
      if (fieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fields_);
      } else {
        return fieldsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public int getFieldsCount() {
      if (fieldsBuilder_ == null) {
        return fields_.size();
      } else {
        return fieldsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef getFields(int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);
      } else {
        return fieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder setFields(
        int index, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder setFields(
        int index, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder addFields(com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder addFields(
        int index, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(index, value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder addFields(
        com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder addFields(
        int index, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder addAllFields(
        Iterable<? extends com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef> values) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        addAll(
            values, fields_);
        onChanged();
      } else {
        fieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder clearFields() {
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public Builder removeFields(int index) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.remove(index);
        onChanged();
      } else {
        fieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder getFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder getFieldsOrBuilder(
        int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);  } else {
        return fieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder> 
         getFieldsOrBuilderList() {
      if (fieldsBuilder_ != null) {
        return fieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fields_);
      }
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder addFieldsBuilder() {
      return getFieldsFieldBuilder().addBuilder(
          com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.getDefaultInstance());
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder addFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().addBuilder(
          index, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.getDefaultInstance());
    }
    /**
     * <pre>
     * Список описания полей
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef fields = 2;</code>
     */
    public java.util.List<com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder> 
         getFieldsBuilderList() {
      return getFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder> 
        getFieldsFieldBuilder() {
      if (fieldsBuilder_ == null) {
        fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder>(
                fields_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fields_ = null;
      }
      return fieldsBuilder_;
    }

    private com.racerssquad.besthack2023.DTO.proto.AdvInfoData data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfoData, com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoDataOrBuilder> dataBuilder_;
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     * @return The data.
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfoData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public Builder setData(com.racerssquad.besthack2023.DTO.proto.AdvInfoData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public Builder setData(
        com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public Builder mergeData(com.racerssquad.besthack2023.DTO.proto.AdvInfoData value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            data_ != null &&
            data_ != com.racerssquad.besthack2023.DTO.proto.AdvInfoData.getDefaultInstance()) {
          data_ =
            com.racerssquad.besthack2023.DTO.proto.AdvInfoData.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder getDataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.racerssquad.besthack2023.DTO.proto.AdvInfoData.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * Данные
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfoData data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfoData, com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.AdvInfoData, com.racerssquad.besthack2023.DTO.proto.AdvInfoData.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.AdvInfo)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.AdvInfo)
  private static final com.racerssquad.besthack2023.DTO.proto.AdvInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.AdvInfo();
  }

  public static com.racerssquad.besthack2023.DTO.proto.AdvInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdvInfo>
      PARSER = new com.google.protobuf.AbstractParser<AdvInfo>() {
    @Override
    public AdvInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdvInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdvInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AdvInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

