// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoFieldRef.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef}
 */
public final class AdvInfoFieldRef extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)
    AdvInfoFieldRefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdvInfoFieldRef.newBuilder() to construct.
  private AdvInfoFieldRef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdvInfoFieldRef() {
    alias_ = "";
    caption_ = "";
    dataType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdvInfoFieldRef();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdvInfoFieldRef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            alias_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            caption_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            dataType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.class, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder.class);
  }

  private int bitField0_;
  public static final int ALIAS_FIELD_NUMBER = 1;
  private volatile Object alias_;
  /**
   * <pre>
   * Идентификатор поля
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  @Override
  public String getAlias() {
    Object ref = alias_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор поля
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  @Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    Object ref = alias_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTION_FIELD_NUMBER = 2;
  private volatile Object caption_;
  /**
   * <pre>
   * Заголовок поля
   * </pre>
   *
   * <code>string caption = 2;</code>
   * @return Whether the caption field is set.
   */
  @Override
  public boolean hasCaption() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Заголовок поля
   * </pre>
   *
   * <code>string caption = 2;</code>
   * @return The caption.
   */
  @Override
  public String getCaption() {
    Object ref = caption_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      caption_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Заголовок поля
   * </pre>
   *
   * <code>string caption = 2;</code>
   * @return The bytes for caption.
   */
  @Override
  public com.google.protobuf.ByteString
      getCaptionBytes() {
    Object ref = caption_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      caption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATATYPE_FIELD_NUMBER = 3;
  private int dataType_;
  /**
   * <pre>
   * Тип данных поля
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  @Override public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <pre>
   * Тип данных поля
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
   * @return The dataType.
   */
  @Override public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.valueOf(dataType_);
    return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAliasBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, caption_);
    }
    if (dataType_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.dtString.getNumber()) {
      output.writeEnum(3, dataType_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAliasBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alias_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, caption_);
    }
    if (dataType_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.dtString.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, dataType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef other = (com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef) obj;

    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (hasCaption() != other.hasCaption()) return false;
    if (hasCaption()) {
      if (!getCaption()
          .equals(other.getCaption())) return false;
    }
    if (dataType_ != other.dataType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    if (hasCaption()) {
      hash = (37 * hash) + CAPTION_FIELD_NUMBER;
      hash = (53 * hash) + getCaption().hashCode();
    }
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)
      com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.class, com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      alias_ = "";

      caption_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      dataType_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRefProto.internal_static_com_racerssquad_besthack2023_DTO_proto_AdvInfoFieldRef_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef build() {
      com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef result = new com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.alias_ = alias_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.caption_ = caption_;
      result.dataType_ = dataType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        onChanged();
      }
      if (other.hasCaption()) {
        bitField0_ |= 0x00000001;
        caption_ = other.caption_;
        onChanged();
      }
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object alias_ = "";
    /**
     * <pre>
     * Идентификатор поля
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The alias.
     */
    public String getAlias() {
      Object ref = alias_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор поля
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор поля
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alias_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор поля
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      
      alias_ = getDefaultInstance().getAlias();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор поля
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alias_ = value;
      onChanged();
      return this;
    }

    private Object caption_ = "";
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @return Whether the caption field is set.
     */
    public boolean hasCaption() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @return The caption.
     */
    public String getCaption() {
      Object ref = caption_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        caption_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @return The bytes for caption.
     */
    public com.google.protobuf.ByteString
        getCaptionBytes() {
      Object ref = caption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        caption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @param value The caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaption(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      caption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCaption() {
      bitField0_ = (bitField0_ & ~0x00000001);
      caption_ = getDefaultInstance().getCaption();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Заголовок поля
     * </pre>
     *
     * <code>string caption = 2;</code>
     * @param value The bytes for caption to set.
     * @return This builder for chaining.
     */
    public Builder setCaptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      caption_ = value;
      onChanged();
      return this;
    }

    private int dataType_ = 0;
    /**
     * <pre>
     * Тип данных поля
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     * Тип данных поля
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
     * @param value The enum numeric value on the wire for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeValue(int value) {
      
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип данных поля
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
     * @return The dataType.
     */
    @Override
    public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.valueOf(dataType_);
      return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип данных поля
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип данных поля
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.DataType dataType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {
      
      dataType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef)
  private static final com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef();
  }

  public static com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdvInfoFieldRef>
      PARSER = new com.google.protobuf.AbstractParser<AdvInfoFieldRef>() {
    @Override
    public AdvInfoFieldRef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdvInfoFieldRef(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdvInfoFieldRef> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AdvInfoFieldRef> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoFieldRef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

