// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * <pre>
 **
 *Заголовок сообщения.
 *Поля: messageNum, timestamp, sender, receiver - не должны быть пустыми.
 *Поле  messageNumAnswer - заполняется на основании поля messageNum сообщения на которое формируется ответ.
 *Данное поле заполняется только для сообщений response.
 * </pre>
 *
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    messageNum_ = "";
    sender_ = "";
    receiver_ = "";
    messageNumAnswer_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Header(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            messageNum_ = s;
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            sender_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            receiver_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            messageNumAnswer_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.HeaderProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Header_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.HeaderProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.Header.class, com.racerssquad.besthack2023.DTO.proto.Header.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGENUM_FIELD_NUMBER = 1;
  private volatile Object messageNum_;
  /**
   * <pre>
   * Номер сообщения
   * </pre>
   *
   * <code>string messageNum = 1;</code>
   * @return The messageNum.
   */
  @Override
  public String getMessageNum() {
    Object ref = messageNum_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      messageNum_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Номер сообщения
   * </pre>
   *
   * <code>string messageNum = 1;</code>
   * @return The bytes for messageNum.
   */
  @Override
  public com.google.protobuf.ByteString
      getMessageNumBytes() {
    Object ref = messageNum_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      messageNum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <pre>
   * Время создания сообщения в миллисекундах от начала эпохи.
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SENDER_FIELD_NUMBER = 3;
  private volatile Object sender_;
  /**
   * <pre>
   * Идентификатор отправителя
   * </pre>
   *
   * <code>string sender = 3;</code>
   * @return The sender.
   */
  @Override
  public String getSender() {
    Object ref = sender_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор отправителя
   * </pre>
   *
   * <code>string sender = 3;</code>
   * @return The bytes for sender.
   */
  @Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    Object ref = sender_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_FIELD_NUMBER = 4;
  private volatile Object receiver_;
  /**
   * <pre>
   * Идентификатор получателя
   * </pre>
   *
   * <code>string receiver = 4;</code>
   * @return The receiver.
   */
  @Override
  public String getReceiver() {
    Object ref = receiver_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      receiver_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор получателя
   * </pre>
   *
   * <code>string receiver = 4;</code>
   * @return The bytes for receiver.
   */
  @Override
  public com.google.protobuf.ByteString
      getReceiverBytes() {
    Object ref = receiver_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      receiver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGENUMANSWER_FIELD_NUMBER = 5;
  private volatile Object messageNumAnswer_;
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>string messageNumAnswer = 5;</code>
   * @return Whether the messageNumAnswer field is set.
   */
  @Override
  public boolean hasMessageNumAnswer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>string messageNumAnswer = 5;</code>
   * @return The messageNumAnswer.
   */
  @Override
  public String getMessageNumAnswer() {
    Object ref = messageNumAnswer_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      messageNumAnswer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Номер сообщения на которое сформирован ответ
   * </pre>
   *
   * <code>string messageNumAnswer = 5;</code>
   * @return The bytes for messageNumAnswer.
   */
  @Override
  public com.google.protobuf.ByteString
      getMessageNumAnswerBytes() {
    Object ref = messageNumAnswer_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      messageNumAnswer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMessageNumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageNum_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (!getSenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sender_);
    }
    if (!getReceiverBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiver_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messageNumAnswer_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMessageNumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageNum_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (!getSenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sender_);
    }
    if (!getReceiverBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiver_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messageNumAnswer_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.Header)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.Header other = (com.racerssquad.besthack2023.DTO.proto.Header) obj;

    if (!getMessageNum()
        .equals(other.getMessageNum())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getReceiver()
        .equals(other.getReceiver())) return false;
    if (hasMessageNumAnswer() != other.hasMessageNumAnswer()) return false;
    if (hasMessageNumAnswer()) {
      if (!getMessageNumAnswer()
          .equals(other.getMessageNumAnswer())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGENUM_FIELD_NUMBER;
    hash = (53 * hash) + getMessageNum().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
    hash = (53 * hash) + getReceiver().hashCode();
    if (hasMessageNumAnswer()) {
      hash = (37 * hash) + MESSAGENUMANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getMessageNumAnswer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *Заголовок сообщения.
   *Поля: messageNum, timestamp, sender, receiver - не должны быть пустыми.
   *Поле  messageNumAnswer - заполняется на основании поля messageNum сообщения на которое формируется ответ.
   *Данное поле заполняется только для сообщений response.
   * </pre>
   *
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.Header)
      com.racerssquad.besthack2023.DTO.proto.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.HeaderProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Header_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.HeaderProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.Header.class, com.racerssquad.besthack2023.DTO.proto.Header.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.Header.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      messageNum_ = "";

      timestamp_ = 0L;

      sender_ = "";

      receiver_ = "";

      messageNumAnswer_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.HeaderProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Header_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Header getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Header build() {
      com.racerssquad.besthack2023.DTO.proto.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Header buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.Header result = new com.racerssquad.besthack2023.DTO.proto.Header(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.messageNum_ = messageNum_;
      result.timestamp_ = timestamp_;
      result.sender_ = sender_;
      result.receiver_ = receiver_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.messageNumAnswer_ = messageNumAnswer_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.Header) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.Header other) {
      if (other == getDefaultInstance()) return this;
      if (!other.getMessageNum().isEmpty()) {
        messageNum_ = other.messageNum_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        onChanged();
      }
      if (!other.getReceiver().isEmpty()) {
        receiver_ = other.receiver_;
        onChanged();
      }
      if (other.hasMessageNumAnswer()) {
        bitField0_ |= 0x00000001;
        messageNumAnswer_ = other.messageNumAnswer_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.Header parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.Header) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object messageNum_ = "";
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return The messageNum.
     */
    public String getMessageNum() {
      Object ref = messageNum_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageNum_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return The bytes for messageNum.
     */
    public com.google.protobuf.ByteString
        getMessageNumBytes() {
      Object ref = messageNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @param value The messageNum to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNum(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageNum() {
      
      messageNum_ = getDefaultInstance().getMessageNum();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения
     * </pre>
     *
     * <code>string messageNum = 1;</code>
     * @param value The bytes for messageNum to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageNum_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Время создания сообщения в миллисекундах от начала эпохи.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private Object sender_ = "";
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return The sender.
     */
    public String getSender() {
      Object ref = sender_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор отправителя
     * </pre>
     *
     * <code>string sender = 3;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sender_ = value;
      onChanged();
      return this;
    }

    private Object receiver_ = "";
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return The receiver.
     */
    public String getReceiver() {
      Object ref = receiver_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return The bytes for receiver.
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @param value The receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiver(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiver_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiver() {
      
      receiver_ = getDefaultInstance().getReceiver();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор получателя
     * </pre>
     *
     * <code>string receiver = 4;</code>
     * @param value The bytes for receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiver_ = value;
      onChanged();
      return this;
    }

    private Object messageNumAnswer_ = "";
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @return Whether the messageNumAnswer field is set.
     */
    public boolean hasMessageNumAnswer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @return The messageNumAnswer.
     */
    public String getMessageNumAnswer() {
      Object ref = messageNumAnswer_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageNumAnswer_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @return The bytes for messageNumAnswer.
     */
    public com.google.protobuf.ByteString
        getMessageNumAnswerBytes() {
      Object ref = messageNumAnswer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageNumAnswer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @param value The messageNumAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumAnswer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      messageNumAnswer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageNumAnswer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageNumAnswer_ = getDefaultInstance().getMessageNumAnswer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер сообщения на которое сформирован ответ
     * </pre>
     *
     * <code>string messageNumAnswer = 5;</code>
     * @param value The bytes for messageNumAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNumAnswerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      messageNumAnswer_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.Header)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.Header)
  private static final com.racerssquad.besthack2023.DTO.proto.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.Header();
  }

  public static com.racerssquad.besthack2023.DTO.proto.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Header(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

