// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    command_ = 0;
    supportedCommands_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 18: {
            com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = commandForExec_.toBuilder();
            }
            commandForExec_ = input.readMessage(com.racerssquad.besthack2023.DTO.proto.OwnCommand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commandForExec_);
              commandForExec_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              supportedCommands_ = new java.util.ArrayList<com.racerssquad.besthack2023.DTO.proto.OwnCommand>();
              mutable_bitField0_ |= 0x00000002;
            }
            supportedCommands_.add(
                input.readMessage(com.racerssquad.besthack2023.DTO.proto.OwnCommand.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        supportedCommands_ = java.util.Collections.unmodifiableList(supportedCommands_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.RequestProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Request_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.RequestProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.Request.class, com.racerssquad.besthack2023.DTO.proto.Request.Builder.class);
  }

  private int bitField0_;
  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  @Override public int getCommandValue() {
    return command_;
  }
  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The command.
   */
  @Override public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType getCommand() {
    @SuppressWarnings("deprecation")
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.valueOf(command_);
    return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
  }

  public static final int COMMANDFOREXEC_FIELD_NUMBER = 2;
  private com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec_;
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   * @return Whether the commandForExec field is set.
   */
  @Override
  public boolean hasCommandForExec() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   * @return The commandForExec.
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.OwnCommand getCommandForExec() {
    return commandForExec_ == null ? com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance() : commandForExec_;
  }
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getCommandForExecOrBuilder() {
    return commandForExec_ == null ? com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance() : commandForExec_;
  }

  public static final int SUPPORTEDCOMMANDS_FIELD_NUMBER = 3;
  private java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand> supportedCommands_;
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  @Override
  public java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand> getSupportedCommandsList() {
    return supportedCommands_;
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  @Override
  public java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> 
      getSupportedCommandsOrBuilderList() {
    return supportedCommands_;
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  @Override
  public int getSupportedCommandsCount() {
    return supportedCommands_.size();
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.OwnCommand getSupportedCommands(int index) {
    return supportedCommands_.get(index);
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getSupportedCommandsOrBuilder(
      int index) {
    return supportedCommands_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getCommandForExec());
    }
    for (int i = 0; i < supportedCommands_.size(); i++) {
      output.writeMessage(3, supportedCommands_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCommandForExec());
    }
    for (int i = 0; i < supportedCommands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, supportedCommands_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.Request)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.Request other = (com.racerssquad.besthack2023.DTO.proto.Request) obj;

    if (command_ != other.command_) return false;
    if (hasCommandForExec() != other.hasCommandForExec()) return false;
    if (hasCommandForExec()) {
      if (!getCommandForExec()
          .equals(other.getCommandForExec())) return false;
    }
    if (!getSupportedCommandsList()
        .equals(other.getSupportedCommandsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    if (hasCommandForExec()) {
      hash = (37 * hash) + COMMANDFOREXEC_FIELD_NUMBER;
      hash = (53 * hash) + getCommandForExec().hashCode();
    }
    if (getSupportedCommandsCount() > 0) {
      hash = (37 * hash) + SUPPORTEDCOMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getSupportedCommandsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.Request)
      com.racerssquad.besthack2023.DTO.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.RequestProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.RequestProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.Request.class, com.racerssquad.besthack2023.DTO.proto.Request.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommandForExecFieldBuilder();
        getSupportedCommandsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      command_ = 0;

      if (commandForExecBuilder_ == null) {
        commandForExec_ = null;
      } else {
        commandForExecBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (supportedCommandsBuilder_ == null) {
        supportedCommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        supportedCommandsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.RequestProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Request_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Request getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Request build() {
      com.racerssquad.besthack2023.DTO.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Request buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.Request result = new com.racerssquad.besthack2023.DTO.proto.Request(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.command_ = command_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (commandForExecBuilder_ == null) {
          result.commandForExec_ = commandForExec_;
        } else {
          result.commandForExec_ = commandForExecBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (supportedCommandsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          supportedCommands_ = java.util.Collections.unmodifiableList(supportedCommands_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.supportedCommands_ = supportedCommands_;
      } else {
        result.supportedCommands_ = supportedCommandsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.Request) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.Request other) {
      if (other == getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.hasCommandForExec()) {
        mergeCommandForExec(other.getCommandForExec());
      }
      if (supportedCommandsBuilder_ == null) {
        if (!other.supportedCommands_.isEmpty()) {
          if (supportedCommands_.isEmpty()) {
            supportedCommands_ = other.supportedCommands_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSupportedCommandsIsMutable();
            supportedCommands_.addAll(other.supportedCommands_);
          }
          onChanged();
        }
      } else {
        if (!other.supportedCommands_.isEmpty()) {
          if (supportedCommandsBuilder_.isEmpty()) {
            supportedCommandsBuilder_.dispose();
            supportedCommandsBuilder_ = null;
            supportedCommands_ = other.supportedCommands_;
            bitField0_ = (bitField0_ & ~0x00000002);
            supportedCommandsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSupportedCommandsFieldBuilder() : null;
          } else {
            supportedCommandsBuilder_.addAllMessages(other.supportedCommands_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int command_ = 0;
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @Override public int getCommandValue() {
      return command_;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return The command.
     */
    @Override
    public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType getCommand() {
      @SuppressWarnings("deprecation")
      com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.valueOf(command_);
      return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> commandForExecBuilder_;
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     * @return Whether the commandForExec field is set.
     */
    public boolean hasCommandForExec() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     * @return The commandForExec.
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand getCommandForExec() {
      if (commandForExecBuilder_ == null) {
        return commandForExec_ == null ? com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance() : commandForExec_;
      } else {
        return commandForExecBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder setCommandForExec(com.racerssquad.besthack2023.DTO.proto.OwnCommand value) {
      if (commandForExecBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commandForExec_ = value;
        onChanged();
      } else {
        commandForExecBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder setCommandForExec(
        com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder builderForValue) {
      if (commandForExecBuilder_ == null) {
        commandForExec_ = builderForValue.build();
        onChanged();
      } else {
        commandForExecBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder mergeCommandForExec(com.racerssquad.besthack2023.DTO.proto.OwnCommand value) {
      if (commandForExecBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            commandForExec_ != null &&
            commandForExec_ != com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance()) {
          commandForExec_ =
            com.racerssquad.besthack2023.DTO.proto.OwnCommand.newBuilder(commandForExec_).mergeFrom(value).buildPartial();
        } else {
          commandForExec_ = value;
        }
        onChanged();
      } else {
        commandForExecBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder clearCommandForExec() {
      if (commandForExecBuilder_ == null) {
        commandForExec_ = null;
        onChanged();
      } else {
        commandForExecBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder getCommandForExecBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommandForExecFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getCommandForExecOrBuilder() {
      if (commandForExecBuilder_ != null) {
        return commandForExecBuilder_.getMessageOrBuilder();
      } else {
        return commandForExec_ == null ?
            com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance() : commandForExec_;
      }
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.OwnCommand commandForExec = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> 
        getCommandForExecFieldBuilder() {
      if (commandForExecBuilder_ == null) {
        commandForExecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder>(
                getCommandForExec(),
                getParentForChildren(),
                isClean());
        commandForExec_ = null;
      }
      return commandForExecBuilder_;
    }

    private java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand> supportedCommands_ =
      java.util.Collections.emptyList();
    private void ensureSupportedCommandsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        supportedCommands_ = new java.util.ArrayList<com.racerssquad.besthack2023.DTO.proto.OwnCommand>(supportedCommands_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> supportedCommandsBuilder_;

    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand> getSupportedCommandsList() {
      if (supportedCommandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(supportedCommands_);
      } else {
        return supportedCommandsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public int getSupportedCommandsCount() {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.size();
      } else {
        return supportedCommandsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand getSupportedCommands(int index) {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.get(index);
      } else {
        return supportedCommandsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder setSupportedCommands(
        int index, com.racerssquad.besthack2023.DTO.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.set(index, value);
        onChanged();
      } else {
        supportedCommandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder setSupportedCommands(
        int index, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.set(index, builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(com.racerssquad.besthack2023.DTO.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(value);
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        int index, com.racerssquad.besthack2023.DTO.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(index, value);
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        int index, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(index, builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addAllSupportedCommands(
        Iterable<? extends com.racerssquad.besthack2023.DTO.proto.OwnCommand> values) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        addAll(
            values, supportedCommands_);
        onChanged();
      } else {
        supportedCommandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder clearSupportedCommands() {
      if (supportedCommandsBuilder_ == null) {
        supportedCommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        supportedCommandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder removeSupportedCommands(int index) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.remove(index);
        onChanged();
      } else {
        supportedCommandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder getSupportedCommandsBuilder(
        int index) {
      return getSupportedCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder getSupportedCommandsOrBuilder(
        int index) {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.get(index);  } else {
        return supportedCommandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<? extends com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> 
         getSupportedCommandsOrBuilderList() {
      if (supportedCommandsBuilder_ != null) {
        return supportedCommandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(supportedCommands_);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder addSupportedCommandsBuilder() {
      return getSupportedCommandsFieldBuilder().addBuilder(
          com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance());
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder addSupportedCommandsBuilder(
        int index) {
      return getSupportedCommandsFieldBuilder().addBuilder(
          index, com.racerssquad.besthack2023.DTO.proto.OwnCommand.getDefaultInstance());
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.racerssquad.besthack2023.DTO.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder> 
         getSupportedCommandsBuilderList() {
      return getSupportedCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder> 
        getSupportedCommandsFieldBuilder() {
      if (supportedCommandsBuilder_ == null) {
        supportedCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.OwnCommand, com.racerssquad.besthack2023.DTO.proto.OwnCommand.Builder, com.racerssquad.besthack2023.DTO.proto.OwnCommandOrBuilder>(
                supportedCommands_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        supportedCommands_ = null;
      }
      return supportedCommandsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.Request)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.Request)
  private static final com.racerssquad.besthack2023.DTO.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.Request();
  }

  public static com.racerssquad.besthack2023.DTO.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

