// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    command_ = 0;
    answerType_ = 0;
    errorText_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            answerType_ = rawValue;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            errorText_ = s;
            break;
          }
          case 34: {
            com.racerssquad.besthack2023.DTO.proto.Status.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.racerssquad.besthack2023.DTO.proto.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.ResponseProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Response_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.ResponseProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.Response.class, com.racerssquad.besthack2023.DTO.proto.Response.Builder.class);
  }

  private int bitField0_;
  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <pre>
   * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  @Override public int getCommandValue() {
    return command_;
  }
  /**
   * <pre>
   * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
   * @return The command.
   */
  @Override public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType getCommand() {
    @SuppressWarnings("deprecation")
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.valueOf(command_);
    return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
  }

  public static final int ANSWERTYPE_FIELD_NUMBER = 2;
  private int answerType_;
  /**
   * <pre>
   * Тип ответа
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
   * @return The enum numeric value on the wire for answerType.
   */
  @Override public int getAnswerTypeValue() {
    return answerType_;
  }
  /**
   * <pre>
   * Тип ответа
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
   * @return The answerType.
   */
  @Override public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType getAnswerType() {
    @SuppressWarnings("deprecation")
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.valueOf(answerType_);
    return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.UNRECOGNIZED : result;
  }

  public static final int ERRORTEXT_FIELD_NUMBER = 3;
  private volatile Object errorText_;
  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>string errorText = 3;</code>
   * @return Whether the errorText field is set.
   */
  @Override
  public boolean hasErrorText() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>string errorText = 3;</code>
   * @return The errorText.
   */
  @Override
  public String getErrorText() {
    Object ref = errorText_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      errorText_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
   * </pre>
   *
   * <code>string errorText = 3;</code>
   * @return The bytes for errorText.
   */
  @Override
  public com.google.protobuf.ByteString
      getErrorTextBytes() {
    Object ref = errorText_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      errorText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private com.racerssquad.besthack2023.DTO.proto.Status status_;
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
   * @return Whether the status field is set.
   */
  @Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
   * @return The status.
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.Status getStatus() {
    return status_ == null ? com.racerssquad.besthack2023.DTO.proto.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? com.racerssquad.besthack2023.DTO.proto.Status.getDefaultInstance() : status_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (answerType_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.atNotSupported.getNumber()) {
      output.writeEnum(2, answerType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorText_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getStatus());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (answerType_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.atNotSupported.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, answerType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorText_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.Response)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.Response other = (com.racerssquad.besthack2023.DTO.proto.Response) obj;

    if (command_ != other.command_) return false;
    if (answerType_ != other.answerType_) return false;
    if (hasErrorText() != other.hasErrorText()) return false;
    if (hasErrorText()) {
      if (!getErrorText()
          .equals(other.getErrorText())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (37 * hash) + ANSWERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + answerType_;
    if (hasErrorText()) {
      hash = (37 * hash) + ERRORTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getErrorText().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.Response)
      com.racerssquad.besthack2023.DTO.proto.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.ResponseProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.ResponseProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.Response.class, com.racerssquad.besthack2023.DTO.proto.Response.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStatusFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      command_ = 0;

      answerType_ = 0;

      errorText_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.ResponseProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Response_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Response getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Response build() {
      com.racerssquad.besthack2023.DTO.proto.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Response buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.Response result = new com.racerssquad.besthack2023.DTO.proto.Response(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.command_ = command_;
      result.answerType_ = answerType_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.errorText_ = errorText_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.Response) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.Response other) {
      if (other == getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.answerType_ != 0) {
        setAnswerTypeValue(other.getAnswerTypeValue());
      }
      if (other.hasErrorText()) {
        bitField0_ |= 0x00000001;
        errorText_ = other.errorText_;
        onChanged();
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int command_ = 0;
    /**
     * <pre>
     * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @Override public int getCommandValue() {
      return command_;
    }
    /**
     * <pre>
     * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return The command.
     */
    @Override
    public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType getCommand() {
      @SuppressWarnings("deprecation")
      com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.valueOf(command_);
      return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды на которую отвечаем. (ctHandshake - ответ на приветствие, ctExecCommand - ответ на исполнение команды, ctStatus - ответ на запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.CommandType command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private int answerType_ = 0;
    /**
     * <pre>
     * Тип ответа
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
     * @return The enum numeric value on the wire for answerType.
     */
    @Override public int getAnswerTypeValue() {
      return answerType_;
    }
    /**
     * <pre>
     * Тип ответа
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
     * @param value The enum numeric value on the wire for answerType to set.
     * @return This builder for chaining.
     */
    public Builder setAnswerTypeValue(int value) {
      
      answerType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип ответа
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
     * @return The answerType.
     */
    @Override
    public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType getAnswerType() {
      @SuppressWarnings("deprecation")
      com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.valueOf(answerType_);
      return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип ответа
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
     * @param value The answerType to set.
     * @return This builder for chaining.
     */
    public Builder setAnswerType(com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.AnswerType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      answerType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип ответа
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AnswerType answerType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnswerType() {
      
      answerType_ = 0;
      onChanged();
      return this;
    }

    private Object errorText_ = "";
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @return Whether the errorText field is set.
     */
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @return The errorText.
     */
    public String getErrorText() {
      Object ref = errorText_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorText_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @return The bytes for errorText.
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      Object ref = errorText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @param value The errorText to set.
     * @return This builder for chaining.
     */
    public Builder setErrorText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      errorText_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorText() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorText_ = getDefaultInstance().getErrorText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание ошибки в случае если тип ответа atNotSupported или atAnswerError
     * </pre>
     *
     * <code>string errorText = 3;</code>
     * @param value The bytes for errorText to set.
     * @return This builder for chaining.
     */
    public Builder setErrorTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      errorText_ = value;
      onChanged();
      return this;
    }

    private com.racerssquad.besthack2023.DTO.proto.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.Status, com.racerssquad.besthack2023.DTO.proto.Status.Builder, com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     * @return The status.
     */
    public com.racerssquad.besthack2023.DTO.proto.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.racerssquad.besthack2023.DTO.proto.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public Builder setStatus(com.racerssquad.besthack2023.DTO.proto.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public Builder setStatus(
        com.racerssquad.besthack2023.DTO.proto.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public Builder mergeStatus(com.racerssquad.besthack2023.DTO.proto.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            status_ != null &&
            status_ != com.racerssquad.besthack2023.DTO.proto.Status.getDefaultInstance()) {
          status_ =
            com.racerssquad.besthack2023.DTO.proto.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.racerssquad.besthack2023.DTO.proto.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * Статус
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.Status status = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.Status, com.racerssquad.besthack2023.DTO.proto.Status.Builder, com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.Status, com.racerssquad.besthack2023.DTO.proto.Status.Builder, com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.Response)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.Response)
  private static final com.racerssquad.besthack2023.DTO.proto.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.Response();
  }

  public static com.racerssquad.besthack2023.DTO.proto.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

