// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

package com.racerssquad.besthack2023.DTO.proto;

/**
 * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Status}
 */
public final class Status extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.racerssquad.besthack2023.DTO.proto.Status)
    StatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Status.newBuilder() to construct.
  private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Status() {
    type_ = 0;
    details_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Status();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Status(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            details_ = s;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            nextTime_ = input.readInt64();
            break;
          }
          case 34: {
            com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = advStatus_.toBuilder();
            }
            advStatus_ = input.readMessage(com.racerssquad.besthack2023.DTO.proto.AdvInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(advStatus_);
              advStatus_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.racerssquad.besthack2023.DTO.proto.StatusProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Status_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.racerssquad.besthack2023.DTO.proto.StatusProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Status_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.racerssquad.besthack2023.DTO.proto.Status.class, com.racerssquad.besthack2023.DTO.proto.Status.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * Тип статуса сервиса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Тип статуса сервиса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
   * @return The type.
   */
  @Override public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType getType() {
    @SuppressWarnings("deprecation")
    com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.valueOf(type_);
    return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.UNRECOGNIZED : result;
  }

  public static final int DETAILS_FIELD_NUMBER = 2;
  private volatile Object details_;
  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>string details = 2;</code>
   * @return Whether the details field is set.
   */
  @Override
  public boolean hasDetails() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>string details = 2;</code>
   * @return The details.
   */
  @Override
  public String getDetails() {
    Object ref = details_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      details_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Детальное описание статуса сервиса
   * </pre>
   *
   * <code>string details = 2;</code>
   * @return The bytes for details.
   */
  @Override
  public com.google.protobuf.ByteString
      getDetailsBytes() {
    Object ref = details_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      details_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEXTTIME_FIELD_NUMBER = 3;
  private long nextTime_;
  /**
   * <pre>
   * Время следующей отправки статуса
   * </pre>
   *
   * <code>int64 nextTime = 3;</code>
   * @return Whether the nextTime field is set.
   */
  @Override
  public boolean hasNextTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Время следующей отправки статуса
   * </pre>
   *
   * <code>int64 nextTime = 3;</code>
   * @return The nextTime.
   */
  @Override
  public long getNextTime() {
    return nextTime_;
  }

  public static final int ADVSTATUS_FIELD_NUMBER = 4;
  private com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus_;
  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   * @return Whether the advStatus field is set.
   */
  @Override
  public boolean hasAdvStatus() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   * @return The advStatus.
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfo getAdvStatus() {
    return advStatus_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfo.getDefaultInstance() : advStatus_;
  }
  /**
   * <pre>
   * Расширенная информация статуса
   * </pre>
   *
   * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
   */
  @Override
  public com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder getAdvStatusOrBuilder() {
    return advStatus_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfo.getDefaultInstance() : advStatus_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.stNotReady.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, details_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(3, nextTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getAdvStatus());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.stNotReady.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, details_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, nextTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAdvStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.racerssquad.besthack2023.DTO.proto.Status)) {
      return super.equals(obj);
    }
    com.racerssquad.besthack2023.DTO.proto.Status other = (com.racerssquad.besthack2023.DTO.proto.Status) obj;

    if (type_ != other.type_) return false;
    if (hasDetails() != other.hasDetails()) return false;
    if (hasDetails()) {
      if (!getDetails()
          .equals(other.getDetails())) return false;
    }
    if (hasNextTime() != other.hasNextTime()) return false;
    if (hasNextTime()) {
      if (getNextTime()
          != other.getNextTime()) return false;
    }
    if (hasAdvStatus() != other.hasAdvStatus()) return false;
    if (hasAdvStatus()) {
      if (!getAdvStatus()
          .equals(other.getAdvStatus())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasDetails()) {
      hash = (37 * hash) + DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getDetails().hashCode();
    }
    if (hasNextTime()) {
      hash = (37 * hash) + NEXTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextTime());
    }
    if (hasAdvStatus()) {
      hash = (37 * hash) + ADVSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getAdvStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.racerssquad.besthack2023.DTO.proto.Status parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.racerssquad.besthack2023.DTO.proto.Status prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.racerssquad.besthack2023.DTO.proto.Status}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.racerssquad.besthack2023.DTO.proto.Status)
      com.racerssquad.besthack2023.DTO.proto.StatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.racerssquad.besthack2023.DTO.proto.StatusProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Status_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.racerssquad.besthack2023.DTO.proto.StatusProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.racerssquad.besthack2023.DTO.proto.Status.class, com.racerssquad.besthack2023.DTO.proto.Status.Builder.class);
    }

    // Construct using com.racerssquad.besthack2023.DTO.proto.Status.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAdvStatusFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      details_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      nextTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (advStatusBuilder_ == null) {
        advStatus_ = null;
      } else {
        advStatusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.racerssquad.besthack2023.DTO.proto.StatusProto.internal_static_com_racerssquad_besthack2023_DTO_proto_Status_descriptor;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Status getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Status build() {
      com.racerssquad.besthack2023.DTO.proto.Status result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.racerssquad.besthack2023.DTO.proto.Status buildPartial() {
      com.racerssquad.besthack2023.DTO.proto.Status result = new com.racerssquad.besthack2023.DTO.proto.Status(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.details_ = details_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nextTime_ = nextTime_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (advStatusBuilder_ == null) {
          result.advStatus_ = advStatus_;
        } else {
          result.advStatus_ = advStatusBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.racerssquad.besthack2023.DTO.proto.Status) {
        return mergeFrom((com.racerssquad.besthack2023.DTO.proto.Status)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.racerssquad.besthack2023.DTO.proto.Status other) {
      if (other == getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasDetails()) {
        bitField0_ |= 0x00000001;
        details_ = other.details_;
        onChanged();
      }
      if (other.hasNextTime()) {
        setNextTime(other.getNextTime());
      }
      if (other.hasAdvStatus()) {
        mergeAdvStatus(other.getAdvStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.racerssquad.besthack2023.DTO.proto.Status parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.racerssquad.besthack2023.DTO.proto.Status) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Тип статуса сервиса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Тип статуса сервиса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип статуса сервиса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
     * @return The type.
     */
    @Override
    public com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType getType() {
      @SuppressWarnings("deprecation")
      com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType result = com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.valueOf(type_);
      return result == null ? com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип статуса сервиса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.racerssquad.besthack2023.DTO.proto.MessageEnumsProto.StatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип статуса сервиса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.StatusType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private Object details_ = "";
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @return Whether the details field is set.
     */
    public boolean hasDetails() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @return The details.
     */
    public String getDetails() {
      Object ref = details_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        details_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @return The bytes for details.
     */
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      Object ref = details_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        details_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @param value The details to set.
     * @return This builder for chaining.
     */
    public Builder setDetails(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      details_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetails() {
      bitField0_ = (bitField0_ & ~0x00000001);
      details_ = getDefaultInstance().getDetails();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Детальное описание статуса сервиса
     * </pre>
     *
     * <code>string details = 2;</code>
     * @param value The bytes for details to set.
     * @return This builder for chaining.
     */
    public Builder setDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      details_ = value;
      onChanged();
      return this;
    }

    private long nextTime_ ;
    /**
     * <pre>
     * Время следующей отправки статуса
     * </pre>
     *
     * <code>int64 nextTime = 3;</code>
     * @return Whether the nextTime field is set.
     */
    @Override
    public boolean hasNextTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Время следующей отправки статуса
     * </pre>
     *
     * <code>int64 nextTime = 3;</code>
     * @return The nextTime.
     */
    @Override
    public long getNextTime() {
      return nextTime_;
    }
    /**
     * <pre>
     * Время следующей отправки статуса
     * </pre>
     *
     * <code>int64 nextTime = 3;</code>
     * @param value The nextTime to set.
     * @return This builder for chaining.
     */
    public Builder setNextTime(long value) {
      bitField0_ |= 0x00000002;
      nextTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Время следующей отправки статуса
     * </pre>
     *
     * <code>int64 nextTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nextTime_ = 0L;
      onChanged();
      return this;
    }

    private com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfo, com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder> advStatusBuilder_;
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     * @return Whether the advStatus field is set.
     */
    public boolean hasAdvStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     * @return The advStatus.
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfo getAdvStatus() {
      if (advStatusBuilder_ == null) {
        return advStatus_ == null ? com.racerssquad.besthack2023.DTO.proto.AdvInfo.getDefaultInstance() : advStatus_;
      } else {
        return advStatusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public Builder setAdvStatus(com.racerssquad.besthack2023.DTO.proto.AdvInfo value) {
      if (advStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        advStatus_ = value;
        onChanged();
      } else {
        advStatusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public Builder setAdvStatus(
        com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder builderForValue) {
      if (advStatusBuilder_ == null) {
        advStatus_ = builderForValue.build();
        onChanged();
      } else {
        advStatusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public Builder mergeAdvStatus(com.racerssquad.besthack2023.DTO.proto.AdvInfo value) {
      if (advStatusBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            advStatus_ != null &&
            advStatus_ != com.racerssquad.besthack2023.DTO.proto.AdvInfo.getDefaultInstance()) {
          advStatus_ =
            com.racerssquad.besthack2023.DTO.proto.AdvInfo.newBuilder(advStatus_).mergeFrom(value).buildPartial();
        } else {
          advStatus_ = value;
        }
        onChanged();
      } else {
        advStatusBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public Builder clearAdvStatus() {
      if (advStatusBuilder_ == null) {
        advStatus_ = null;
        onChanged();
      } else {
        advStatusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder getAdvStatusBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAdvStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    public com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder getAdvStatusOrBuilder() {
      if (advStatusBuilder_ != null) {
        return advStatusBuilder_.getMessageOrBuilder();
      } else {
        return advStatus_ == null ?
            com.racerssquad.besthack2023.DTO.proto.AdvInfo.getDefaultInstance() : advStatus_;
      }
    }
    /**
     * <pre>
     * Расширенная информация статуса
     * </pre>
     *
     * <code>.com.racerssquad.besthack2023.DTO.proto.AdvInfo advStatus = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.racerssquad.besthack2023.DTO.proto.AdvInfo, com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder> 
        getAdvStatusFieldBuilder() {
      if (advStatusBuilder_ == null) {
        advStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.racerssquad.besthack2023.DTO.proto.AdvInfo, com.racerssquad.besthack2023.DTO.proto.AdvInfo.Builder, com.racerssquad.besthack2023.DTO.proto.AdvInfoOrBuilder>(
                getAdvStatus(),
                getParentForChildren(),
                isClean());
        advStatus_ = null;
      }
      return advStatusBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.racerssquad.besthack2023.DTO.proto.Status)
  }

  // @@protoc_insertion_point(class_scope:com.racerssquad.besthack2023.DTO.proto.Status)
  private static final com.racerssquad.besthack2023.DTO.proto.Status DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.racerssquad.besthack2023.DTO.proto.Status();
  }

  public static com.racerssquad.besthack2023.DTO.proto.Status getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Status>
      PARSER = new com.google.protobuf.AbstractParser<Status>() {
    @Override
    public Status parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Status(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Status> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Status> getParserForType() {
    return PARSER;
  }

  @Override
  public com.racerssquad.besthack2023.DTO.proto.Status getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

